// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tracing.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tracing middleware config.
type Tracing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// report endpoint url
	//
	// Types that are valid to be assigned to Endpoint:
	//
	//	*Tracing_HttpEndpoint
	//	*Tracing_HttpEndpointUrl
	Endpoint isTracing_Endpoint `protobuf_oneof:"endpoint"`
	// sample ratio
	SampleRatio *float32 `protobuf:"fixed32,3,opt,name=sample_ratio,json=sampleRatio,proto3,oneof" json:"sample_ratio,omitempty"`
	// report timeout
	Timeout *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// ssl
	Insecure *bool `protobuf:"varint,5,opt,name=insecure,proto3,oneof" json:"insecure,omitempty"`
	// service name
	ServiceName *string `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3,oneof" json:"service_name,omitempty"`
	// tracer name
	TracerName    *string `protobuf:"bytes,7,opt,name=tracer_name,json=tracerName,proto3,oneof" json:"tracer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tracing) Reset() {
	*x = Tracing{}
	mi := &file_tracing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracing) ProtoMessage() {}

func (x *Tracing) ProtoReflect() protoreflect.Message {
	mi := &file_tracing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracing.ProtoReflect.Descriptor instead.
func (*Tracing) Descriptor() ([]byte, []int) {
	return file_tracing_proto_rawDescGZIP(), []int{0}
}

func (x *Tracing) GetEndpoint() isTracing_Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *Tracing) GetHttpEndpoint() string {
	if x != nil {
		if x, ok := x.Endpoint.(*Tracing_HttpEndpoint); ok {
			return x.HttpEndpoint
		}
	}
	return ""
}

func (x *Tracing) GetHttpEndpointUrl() string {
	if x != nil {
		if x, ok := x.Endpoint.(*Tracing_HttpEndpointUrl); ok {
			return x.HttpEndpointUrl
		}
	}
	return ""
}

func (x *Tracing) GetSampleRatio() float32 {
	if x != nil && x.SampleRatio != nil {
		return *x.SampleRatio
	}
	return 0
}

func (x *Tracing) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Tracing) GetInsecure() bool {
	if x != nil && x.Insecure != nil {
		return *x.Insecure
	}
	return false
}

func (x *Tracing) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *Tracing) GetTracerName() string {
	if x != nil && x.TracerName != nil {
		return *x.TracerName
	}
	return ""
}

type isTracing_Endpoint interface {
	isTracing_Endpoint()
}

type Tracing_HttpEndpoint struct {
	HttpEndpoint string `protobuf:"bytes,1,opt,name=http_endpoint,json=httpEndpoint,proto3,oneof"`
}

type Tracing_HttpEndpointUrl struct {
	HttpEndpointUrl string `protobuf:"bytes,2,opt,name=http_endpoint_url,json=httpEndpointUrl,proto3,oneof"`
}

func (*Tracing_HttpEndpoint) isTracing_Endpoint() {}

func (*Tracing_HttpEndpointUrl) isTracing_Endpoint() {}

var File_tracing_proto protoreflect.FileDescriptor

const file_tracing_proto_rawDesc = "" +
	"\n" +
	"\rtracing.proto\x12\x1dgateway.middleware.tracing.v1\x1a\x1egoogle/protobuf/duration.proto\"\xf5\x02\n" +
	"\aTracing\x12%\n" +
	"\rhttp_endpoint\x18\x01 \x01(\tH\x00R\fhttpEndpoint\x12,\n" +
	"\x11http_endpoint_url\x18\x02 \x01(\tH\x00R\x0fhttpEndpointUrl\x12&\n" +
	"\fsample_ratio\x18\x03 \x01(\x02H\x01R\vsampleRatio\x88\x01\x01\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\binsecure\x18\x05 \x01(\bH\x02R\binsecure\x88\x01\x01\x12&\n" +
	"\fservice_name\x18\x06 \x01(\tH\x03R\vserviceName\x88\x01\x01\x12$\n" +
	"\vtracer_name\x18\a \x01(\tH\x04R\n" +
	"tracerName\x88\x01\x01B\n" +
	"\n" +
	"\bendpointB\x0f\n" +
	"\r_sample_ratioB\v\n" +
	"\t_insecureB\x0f\n" +
	"\r_service_nameB\x0e\n" +
	"\f_tracer_nameB@Z>github.com/go-kratos/gateway/api/gateway/middleware/tracing/v1b\x06proto3"

var (
	file_tracing_proto_rawDescOnce sync.Once
	file_tracing_proto_rawDescData []byte
)

func file_tracing_proto_rawDescGZIP() []byte {
	file_tracing_proto_rawDescOnce.Do(func() {
		file_tracing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracing_proto_rawDesc), len(file_tracing_proto_rawDesc)))
	})
	return file_tracing_proto_rawDescData
}

var file_tracing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tracing_proto_goTypes = []any{
	(*Tracing)(nil),             // 0: gateway.middleware.tracing.v1.Tracing
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_tracing_proto_depIdxs = []int32{
	1, // 0: gateway.middleware.tracing.v1.Tracing.timeout:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tracing_proto_init() }
func file_tracing_proto_init() {
	if File_tracing_proto != nil {
		return
	}
	file_tracing_proto_msgTypes[0].OneofWrappers = []any{
		(*Tracing_HttpEndpoint)(nil),
		(*Tracing_HttpEndpointUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracing_proto_rawDesc), len(file_tracing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracing_proto_goTypes,
		DependencyIndexes: file_tracing_proto_depIdxs,
		MessageInfos:      file_tracing_proto_msgTypes,
	}.Build()
	File_tracing_proto = out.File
	file_tracing_proto_goTypes = nil
	file_tracing_proto_depIdxs = nil
}
