version: '3'
services:
  gateway:
    build: ../../../../
    ports:
      - "8080:8080"
      - "7070:7070"
    volumes:
      - ./cmd/gateway/config.yaml:/data/conf/config.yaml
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: '8192M'
