name: Go

on:
  push:
    branches:
      - init
  pull_request:
    branches:
      - init

jobs:
  Test:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Go Build
        run: go build -v ./...

      - name: Go Vet
        run: go vet ./...

      - name: Go Test
        run: go test -v -cover -race ./...
