name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Build
        run: go build -v ./...

      - name: Go Vet
        run: go vet ./...

      - name: Go Test
        run: go test -v -coverprofile=coverage.out -covermode=atomic -race ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.os }}
